// <auto-generated />
namespace Code_first.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202401222307017_pdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
